dist: trusty
script: "/bin/true"
notifications:
  email: false
  slack:
    rooms:
      secure: N2YZSSQNamiqBY+PGgehoSVlPzFoh/Z65qn2rcAMFXxU5evtDIwphZHIQ9t31QjiBC1V0HBSraiU9aNeibJWthagiwW5ITST20FeMSk6T4MRC+kXCuSxqu2oTb8V7aQcrPMwsosCdu+bBKInXOueLu5xlIa+3t9hMqgXD2jYB/lDFm3nLqokd1IF8R5KDuUcCj18OV9cvYgCtgyyEy1RuVADiTBKXdZt5GkeMuugTt/rD9z939fp6chENrxZVXudZAzS1YZEKfHppJQz+zUHgFRzfRFHcPWB12GyJmoi/xmUSEcjyLYo70LWuhEbaBKHvQC7O3VZ+AWpN7ByJvZAsdC98dBvHsl2yntSmenT3IDsmm3i6/t4vJcILw0uUjlrmFe3Y5/jG3mMkrnvoS0pmR4FMPlf+Iu6wctsG1Fwio9EdDG7t5Eb4wtHEchaOreU0Z9LU5szpR1Q0LtLDCirmdW6G1E/rzLhPlsFV8h7vPWCRyl61axtLOUXn7JhSICgi1HFyKoTg/rJtKfZmOGB3PYmqsq1E59m2TZJYD+wPAMyRz4sU7gT2uNigmDIqEKabt2I/v/BsIqeJz+rEbqcTdwCYrPwz9qH2zdQPTe/bNGb5i7L2FsPciuuVFiW7CxiAuDkvxgCWRUT6RQdqcOBxBUHQpVLxcq6lDgzrcYyA1A=
