dist: xenial
env:
  global:
  - TFBIN_DIR=$HOME/tfbin
  - TERRAFORM_VERSION=0.11.13
install:
- "./scripts/download_terraform.sh $TERRAFORM_VERSION"
script:
- "~/tfbin/terraform fmt -write=false -diff=true -check"
notifications:
  email: false
  slack:
    secure: kAp5N7ULcLbkr7Sc1W2otMDJYVPehRDpE6f/Cj+5239+izs2E+ILgb7EBelbwPYiuOXsii/Zv6e3qiUdmMZy7b2sEA/ESZXMjaFUVaVhTvnwbTa62M9+ziCeAAakIJ7vXQi8zwYPqCkT532Pl2F/edyK+f4R2+VQ4GX3lhr2419MfPSRW0L1YCsKRIQ4oDSL76MIOa6wd2jVADRiAxOGqNcc5MmtQR1BDS3N7XPk47ahfkDNWMjCPB4Nt5LCMEdj8X1C8cpAGgFXOKDVAAqUUb8g4D3Ryal+L6dESD1OWCQtB4WQ0gwaPP9bqq3MnEJdCtgUnk6bxSUJoGq/OVQ4nNSHGdvPp3U6wJbGrEtE5eXQdMK15S0csw9IQjSDvRVk4WscIzk0MFlH1Q6lyCZUNAKZ1sgvoMjIT06r8Hbgo8YvqIInFslWOTxNdeRvZyfhv1bNW4ZUVQC9z52glLvUuV3x+gxuRxzG3iE9lCTG4rrR9y7f4YRvhR2AvKEPOVOkCDAWmaBknNyyLrXrw61Ej5Ou83G7wdiQnWvVAmQKubYGuC37+TaKnv9WpG355MWPfeTIBmd8GNmreZhoyryOLoboeYMv/lsIkIv5ToyX6ZfMCQtNZ3ROrthmmFB6g9/SsFVL4sEjNe5k4lem8x07SSttEj8TZ8tcXBRwvWxQbXk=
